In [2]:
import pandas as pd

In [5]:
ebell_data = pd.read_csv("/home/vs428/project/Uncertainty_data/penumonia_all_cases.csv", sep="|",  engine="c")

In [6]:
jbrush_data = pd.read_csv("/home/vs428/project/Uncertainty_data/all_cases.csv", sep="|",  engine="c")

In [10]:
ebell_data.head()

,note_id,scenario,probability_q,management_q,valupdate_management_q,management_option_1,management_option_2,management_option_3,true_pretest
0,1,A patient presents with a 3 day history of cou...,The probability of community acquired pneumoni...,"Based on this probability, you choose the foll...",Based on a validated clinical decision rule th...,"You feel that CAP is adequately ruled out, no ...",You order an CXR to evaluate for possible CAP,You feel that CAP is likely enough to prescrib...,2
1,2,A patient presents with a 3 day history of cou...,The probability of community acquired pneumoni...,"Based on this probability, you choose the foll...",Based on a validated clinical decision rule th...,"You feel that CAP is adequately ruled out, no ...",You order an CXR to evaluate for possible CAP,You feel that CAP is likely enough to prescrib...,17
2,3,A patient presents with a 3 day history of cou...,The probability of community acquired pneumoni...,"Based on this probability, you choose the foll...",Based on a validated clinical decision rule th...,"You feel that CAP is adequately ruled out, no ...",You order an CXR to evaluate for possible CAP,You feel that CAP is likely enough to prescrib...,45
3,4,A patient presents with a 3 day history of cou...,The probability of community acquired pneumoni...,"Based on this probability, you choose the foll...",Based on a validated clinical decision rule th...,"You feel that CAP is adequately ruled out, no ...",You order an CXR to evaluate for possible CAP,You feel that CAP is likely enough to prescrib...,5
4,5,A patient presents with a 3 day history of cou...,The probability of community acquired pneumoni...,"Based on this probability, you choose the foll...",Based on a validated clinical decision rule th...,"You feel that CAP is adequately ruled out, no ...",You order an CXR to evaluate for possible CAP,You feel that CAP is likely enough to prescrib...,24

In [11]:
jbrush_data.head()

,index,case_id,case_type,probability,differential,case,lab_value_text,q1,q2,pos_lr,neg_lr
0,0,1,ACS,low,most likely anxiety,A 28 year-old woman presents to the ED with a ...,A troponin level was drawn and reported back f...,What is the probability that this patient has ...,Now what is the probability that this patient ...,4.75,0.25
1,1,2,ACS,low,most likely pericarditis,A 35 year-old man presents to the ED with a 3-...,A troponin level was drawn and reported back f...,What is the probability that this patient has ...,Now what is the probability that this patient ...,4.75,0.25
2,2,3,ACS,low,most likely GERD,A 50 year-old woman presents to the ED with a ...,A troponin level was drawn and reported back f...,What is the probability that this patient has ...,Now what is the probability that this patient ...,4.75,0.25
3,3,4,ACS,low,likely musculoskeletal,A 50 year-old man presents to the ED with ches...,A troponin level was drawn and reported back f...,What is the probability that this patient has ...,Now what is the probability that this patient ...,4.75,0.25
4,4,5,ACS,medium,ACS versus hypertensive emergency,A 50 year-old woman presents to the ED with ch...,A troponin level was drawn and reported back f...,What is the probability that this patient has ...,Now what is the probability that this patient ...,4.75,0.25

In [14]:
jbrush_data['study'] = "JBrush"

In [15]:
ebell_data['study'] = "Ebell"
ebell_data['case_type'] = "PNEUMONIA"

In [18]:
jbrush_data[['case_id', "case_type", "case", "study"]]

,case_id,case_type,case,study
0,1,ACS,A 28 year-old woman presents to the ED with a ...,JBrush
1,2,ACS,A 35 year-old man presents to the ED with a 3-...,JBrush
2,3,ACS,A 50 year-old woman presents to the ED with a ...,JBrush
3,4,ACS,A 50 year-old man presents to the ED with ches...,JBrush
4,5,ACS,A 50 year-old woman presents to the ED with ch...,JBrush
5,6,ACS,A 60 year-old man presents to the ED with ches...,JBrush
6,7,ACS,A 70 year-old woman presents to the ED with ch...,JBrush
7,8,ACS,A 50 year-old man presents to the ED with ches...,JBrush
8,9,ACS,A 70 year-old woman presents to the ED with ch...,JBrush
9,10,ACS,A 50 year-old man presents to the ED with ches...,JBrush
10,11,ACS,A 75 year-old man presents to the ED with ches...,JBrush
11,12,ACS,A 80 year-old woman presents to the ED with ch...,JBrush
12,13,ACS,A 45 year-old man presents to the ED with ches...,JBrush
13,1,CHF,A 28 year-old woman presents to the ED with a ...,JBrush
14,2,CHF,A 68 year-old man presents to the ED with a 3-...,JBrush
15,3,CHF,A 50 year-old woman present to the ED with a 2...,JBrush
16,4,CHF,A 30 year-old man presents to the ED with wors...,JBrush
17,5,CHF,A 25 year-old woman presents to the ED with sh...,JBrush
18,6,CHF,A 60 year-old African American man presents to...,JBrush
19,7,CHF,A 50 year old African American woman presents...,JBrush
20,8,CHF,A 68 year-old man presents to the ED with prog...,JBrush
21,9,CHF,A 70 year-old man presents to the ED with prog...,JBrush
22,10,CHF,A 48 year-old man presents to the ED with prog...,JBrush
23,11,CHF,A 75 year-old woman presents to the ED with pr...,JBrush
24,12,CHF,A 60 year-old man presents to the ED with prog...,JBrush
25,13,CHF,A 80 year-old woman is presents to the ED with...,JBrush
26,1,PNEUMONIA,A 23-year-old woman presents to the emergency ...,JBrush
27,2,PNEUMONIA,A 57-year-old man presents to the emergency de...,JBrush
28,3,PNEUMONIA,A 30-year-old man presents to the emergency de...,JBrush
29,4,PNEUMONIA,A 86-year-old woman is transferred to the emer...,JBrush
30,1,Pulmonary Embolism,A 29-year-old woman presents complaining of ch...,JBrush
31,2,Pulmonary Embolism,A 42 year old man presents with pain in the ri...,JBrush
32,3,Pulmonary Embolism,A 67 year old man presents with retrosternal c...,JBrush
33,4,Pulmonary Embolism,A 45 year old female presents with a 6 day his...,JBrush
34,5,Pulmonary Embolism,A 53-year-old female presents to the emergency...,JBrush
35,6,Pulmonary Embolism,A 37-year-old male presents to the emergency d...,JBrush
36,7,Pulmonary Embolism,A 76 year-old female is brought to the emergen...,JBrush
37,8,Pulmonary Embolism,A 54-year old woman presents to the emergency ...,JBrush
38,9,Pulmonary Embolism,A 33 year old man presents complaining of retr...,JBrush
39,10,Pulmonary Embolism,An 86 year old women presents from home post s...,JBrush
40,11,Pulmonary Embolism,A 29 yo female presents complaining of pleurit...,JBrush
41,12,Pulmonary Embolism,A 54 year old man presents with shortness of b...,JBrush
42,13,Pulmonary Embolism,"A 66 year old female presents with a warm, swo...",JBrush

In [31]:
pd.concat([ebell_data[['note_id', "case_type", "scenario", "study"]].rename({"note_id":"case_id", "scenario":"case"}, axis=1), 
           jbrush_data[['case_id', "case_type", "case", "study"]]],
           axis=0).to_csv("Vignette_Score_Annotations.csv", index=True)

In [30]:
pd.concat([ebell_data[['note_id', "case_type", "scenario", "study"]].rename({"note_id":"case_id", "scenario":"case"}, axis=1), 
           jbrush_data[['case_id', "case_type", "case", "study"]]],
           axis=0)

,case_id,case_type,case,study
0,1,PNEUMONIA,A patient presents with a 3 day history of cou...,Ebell
1,2,PNEUMONIA,A patient presents with a 3 day history of cou...,Ebell
2,3,PNEUMONIA,A patient presents with a 3 day history of cou...,Ebell
3,4,PNEUMONIA,A patient presents with a 3 day history of cou...,Ebell
4,5,PNEUMONIA,A patient presents with a 3 day history of cou...,Ebell
5,6,PNEUMONIA,A patient presents with a 3 day history of cou...,Ebell
6,7,PNEUMONIA,A patient presents with a 3 day history of cou...,Ebell
7,8,PNEUMONIA,A patient presents with a 3 day history of cou...,Ebell
0,1,ACS,A 28 year-old woman presents to the ED with a ...,JBrush
1,2,ACS,A 35 year-old man presents to the ED with a 3-...,JBrush
2,3,ACS,A 50 year-old woman presents to the ED with a ...,JBrush
3,4,ACS,A 50 year-old man presents to the ED with ches...,JBrush
4,5,ACS,A 50 year-old woman presents to the ED with ch...,JBrush
5,6,ACS,A 60 year-old man presents to the ED with ches...,JBrush
6,7,ACS,A 70 year-old woman presents to the ED with ch...,JBrush
7,8,ACS,A 50 year-old man presents to the ED with ches...,JBrush
8,9,ACS,A 70 year-old woman presents to the ED with ch...,JBrush
9,10,ACS,A 50 year-old man presents to the ED with ches...,JBrush
10,11,ACS,A 75 year-old man presents to the ED with ches...,JBrush
11,12,ACS,A 80 year-old woman presents to the ED with ch...,JBrush
12,13,ACS,A 45 year-old man presents to the ED with ches...,JBrush
13,1,CHF,A 28 year-old woman presents to the ED with a ...,JBrush
14,2,CHF,A 68 year-old man presents to the ED with a 3-...,JBrush
15,3,CHF,A 50 year-old woman present to the ED with a 2...,JBrush
16,4,CHF,A 30 year-old man presents to the ED with wors...,JBrush
17,5,CHF,A 25 year-old woman presents to the ED with sh...,JBrush
18,6,CHF,A 60 year-old African American man presents to...,JBrush
19,7,CHF,A 50 year old African American woman presents...,JBrush
20,8,CHF,A 68 year-old man presents to the ED with prog...,JBrush
21,9,CHF,A 70 year-old man presents to the ED with prog...,JBrush
22,10,CHF,A 48 year-old man presents to the ED with prog...,JBrush
23,11,CHF,A 75 year-old woman presents to the ED with pr...,JBrush
24,12,CHF,A 60 year-old man presents to the ED with prog...,JBrush
25,13,CHF,A 80 year-old woman is presents to the ED with...,JBrush
26,1,PNEUMONIA,A 23-year-old woman presents to the emergency ...,JBrush
27,2,PNEUMONIA,A 57-year-old man presents to the emergency de...,JBrush
28,3,PNEUMONIA,A 30-year-old man presents to the emergency de...,JBrush
29,4,PNEUMONIA,A 86-year-old woman is transferred to the emer...,JBrush
30,1,Pulmonary Embolism,A 29-year-old woman presents complaining of ch...,JBrush
31,2,Pulmonary Embolism,A 42 year old man presents with pain in the ri...,JBrush
32,3,Pulmonary Embolism,A 67 year old man presents with retrosternal c...,JBrush
33,4,Pulmonary Embolism,A 45 year old female presents with a 6 day his...,JBrush
34,5,Pulmonary Embolism,A 53-year-old female presents to the emergency...,JBrush
35,6,Pulmonary Embolism,A 37-year-old male presents to the emergency d...,JBrush
36,7,Pulmonary Embolism,A 76 year-old female is brought to the emergen...,JBrush
37,8,Pulmonary Embolism,A 54-year old woman presents to the emergency ...,JBrush
38,9,Pulmonary Embolism,A 33 year old man presents complaining of retr...,JBrush
39,10,Pulmonary Embolism,An 86 year old women presents from home post s...,JBrush
40,11,Pulmonary Embolism,A 29 yo female presents complaining of pleurit...,JBrush
41,12,Pulmonary Embolism,A 54 year old man presents with shortness of b...,JBrush
42,13,Pulmonary Embolism,"A 66 year old female presents with a warm, swo...",JBrush